site_name: Linux Book
theme:
  name: readthedocs
  highlightjs: true
  icon:
    admonition:
        <type>: <icon>
        
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.details
  - pymdownx.superfences


nav:
  - 前言: 
    - '基本介绍': 'index.md'
    - '内核开发准备': 'linux_tools_install.md'
  - 基础机制:
    - '并发同步': 'foundation/lock.md'
    - 'sysfs': 'foundation/sysfs.md'
  - 内存子系统: 
    - '简介': 'mem/index.md'
    - '内存初始化': 'mem/init.md'
    - '物理内存管理': 'mem/physical.md'
    - '物理内存规整': 'mem/compacation.md'
    - '物理内存回收': 'mem/compacation.md'
    - '调试': 'mem/debug.md'
    - '官网翻译': 'mem/doc.md'
  - 驱动子系统:
    - 'dts': 'driver/dts.md'
  - 文件系统:
    - 'nvme': 'fs/nvme.md'
  - ARM异常机制: 
    - '简介': 'interrupt/index.md'
    - 'ARM64单CPU': 'interrupt/arm64.md'
  - DFX:
    - 'gdb': 'debug/gdb.md'
    - 'debug_objects': 'debug/debug_objects.md'
