[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "linux-book"
authors = [{name = "GuoWeikang", email = "guoweikang.kernel@gmail"}]
dynamic = ["version", "description"]
